export const LOAD_ALL_QUESTION_BEGIN = 'LOAD_ALL_QUESTION_BEGIN';
export const LOAD_ALL_QUESTION_SUCCESS = 'LOAD_ALL_QUESTION_SUCCESS';
export const LOAD_ALL_QUESTION_ERROR = 'LOAD_ALL_QUESTION_ERROR';
