export const ANSWER_BEGIN = 'ANSWER_BEGIN';
export const ANSWER_SUCCESS = 'ANSWER_SUCCESS';
export const ANSWER_ERROR = 'ANSWER_ERROR';
export const GET_ANSWERS_BEGIN = 'GET_ANSWERS_BEGIN';
export const GET_ANSWERS_SUCCESS = 'GET_ANSWERS_SUCCESS';
export const GET_ANSWERS_ERROR = 'GET_ANSWERS_ERROR';
