export const LOAD_SINGLE_QUESTION_BEGIN = 'LOAD_SINGLE_QUESTION_BEGIN';
export const LOAD_SINGLE_QUESTION_SUCCESS = 'LOAD_SINGLE_QUESTION_SUCCESS';
export const LOAD_SINGLE_QUESTION_ERROR = 'LOAD_SINGLE_QUESTION_ERROR';
export const DELETE_QUESTION_BEGIN = 'DELETE_QUESTION_BEGIN';
export const DELETE_QUESTION_SUCCESS = 'DELETE_QUESTION_SUCCESS';
export const DELETE_QUESTION_ERROR = 'DELETE_QUESTION_ERROR';
