export const LOAD_SINGLE_QUESTION_BEGIN = 'LOAD_SINGLE_QUESTION_BEGIN';
export const LOAD_SINGLE_QUESTION_SUCCESS = 'LOAD_SINGLE_QUESTION_SUCCESS';
export const LOAD_SINGLE_QUESTION_ERROR = 'LOAD_SINGLE_QUESTION_ERROR';
